[workspace]
members = [
        "bitsplain",
        "bitsplain-bin",
	# "bitsplain-lib",
	# "bitsplain-core",
	# "bitsplain-gtk",
	# "bitsplain-nom",
	# "bitsplain-btc",
	# "bitsplain-ln",
	# "bitsplain-cli"
]